### ISSUE TITLE
使用的时候出现如下错误.at java.lang.String.replaceFirst(String.java:2167)

### ISSUE THREAD

**Issue by Ltaimao** [byzy/jcv-maven-plugin#1]
[err.txt](https://github.com/byzy/jcv-maven-plugin/files/832872/err.txt)
`[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building dianjianbao-web Maven Webapp 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jeecgframework:codegenerate:jar:3.6-20160713.083428-7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dianjianbao-web ---
[INFO] Deleting G:\dianjianbao\dianjianbao-web\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dianjianbao-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\dianjianbao\dianjianbao-web\src\main\java
[INFO] Copying 13 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.4:compile (default-compile) @ dianjianbao-web ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ dianjianbao-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\dianjianbao\dianjianbao-web\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.4:testCompile (default-testCompile) @ dianjianbao-web ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ dianjianbao-web ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-war-plugin:2.6:war (default-war) @ dianjianbao-web ---
[INFO] Packaging webapp
[INFO] Assembling webapp [dianjianbao-web] in [G:\dianjianbao\dianjianbao-web\target\ROOT]
[INFO] Processing war project
[INFO] Copying webapp webResources [G:\dianjianbao\dianjianbao-web/src/main/webapp/mobile/saas/app/js] to [G:\dianjianbao\dianjianbao-web\target\ROOT]
[INFO] Copying webapp resources [G:\dianjianbao\dianjianbao-web\src\main\webapp]
[INFO] Webapp assembled in [15382 msecs]
[INFO] Building war: G:\dianjianbao\dianjianbao-web\target\ROOT.war
[INFO]
[INFO] --- jcv-maven-plugin:0.0.3:process (process) @ dianjianbao-web ---
[INFO] ===================JCV==========================
[INFO]       _  _______      __
[INFO]      | |/ ____\ \    / /
[INFO]      | | |     \ \  / /
[INFO]  _   | | |      \ \/ /
[INFO] | |__| | |____   \  /
[INFO]  \____/ \_____|   \/
[INFO]
[INFO]
[INFO] find suffixs size:1
[INFO] build webRootName:ROOT
[INFO] build sourceEncoding:UTF-8
[INFO] web app Dir:G:\dianjianbao\dianjianbao-web\src\main\webapp
[INFO] out Dir:G:\dianjianbao\dianjianbao-web\target
[INFO] system is linux:false
[INFO] css method is :md5FileName
[INFO] js method is :md5FileName
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.359 s
[INFO] Finished at: 2017-03-10T10:49:57+08:00
[INFO] Final Memory: 11M/34M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:process (process) on project dianjianbao-web: Execution process of goal com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:pr
ocess failed: Illegal/unsupported escape sequence near index 35
[ERROR] G:\dianjianbao\dianjianbao-web\src\main\webapp\
[ERROR] ^
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:process (process) on project dianjianbao-web: Execution process of goal
com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:process failed: Illegal/unsupported escape sequence near index 35
G:\dianjianbao\dianjianbao-web\src\main\webapp\
                                   ^
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution process of goal com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:process failed: Illegal/unsupported escape sequence near index 3
5
G:\dianjianbao\dianjianbao-web\src\main\webapp\
                                   ^
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 35
G:\dianjianbao\dianjianbao-web\src\main\webapp\
                                   ^
        at java.util.regex.Pattern.error(Pattern.java:1924)
        at java.util.regex.Pattern.escape(Pattern.java:2416)
        at java.util.regex.Pattern.atom(Pattern.java:2164)
        at java.util.regex.Pattern.sequence(Pattern.java:2097)
        at java.util.regex.Pattern.expr(Pattern.java:1964)
        at java.util.regex.Pattern.compile(Pattern.java:1665)
        at java.util.regex.Pattern.<init>(Pattern.java:1337)
        at java.util.regex.Pattern.compile(Pattern.java:1022)
        at java.lang.String.replaceFirst(String.java:2167)
        at com.iqarr.maven.plugin.JCVMojo.getAllCssFile(JCVMojo.java:432)
        at com.iqarr.maven.plugin.JCVMojo.execute(JCVMojo.java:184)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
G:\dianjianbao\dianjianbao-web>mvn -e clean package
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building dianjianbao-web Maven Webapp 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jeecgframework:codegenerate:jar:3.6-20160713.083428-7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dianjianbao-web ---
[INFO] Deleting G:\dianjianbao\dianjianbao-web\target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.956 s
[INFO] Finished at: 2017-03-10T10:55:46+08:00
[INFO] Final Memory: 9M/22M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project dianjianbao-web: Failed to clean project: Failed to delete G:\dianjianbao\dianjianbao
-web\target\m2e-wtp\web-resources\plug-in\icheck\square -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project dianjianbao-web: Failed to clean proj
ect: Failed to delete G:\dianjianbao\dianjianbao-web\target\m2e-wtp\web-resources\plug-in\icheck\square
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to clean project: Failed to delete G:\dianjianbao\dianjianbao-web\target\m2e-wtp\web-resources\plug-in\icheck\square
        at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:215)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.io.IOException: Failed to delete G:\dianjianbao\dianjianbao-web\target\m2e-wtp\web-resources\plug-in\icheck\square
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:249)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:191)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:117)
        at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:193)
        ... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
G:\dianjianbao\dianjianbao-web>mvn -e package
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building dianjianbao-web Maven Webapp 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jeecgframework:codegenerate:jar:3.6-20160713.083428-7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dianjianbao-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\dianjianbao\dianjianbao-web\src\main\java
[INFO] Copying 13 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.4:compile (default-compile) @ dianjianbao-web ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ dianjianbao-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\dianjianbao\dianjianbao-web\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.4:testCompile (default-testCompile) @ dianjianbao-web ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ dianjianbao-web ---
[INFO]
[INFO] --- maven-war-plugin:2.6:war (default-war) @ dianjianbao-web ---
[INFO] Packaging webapp
[INFO] Assembling webapp [dianjianbao-web] in [G:\dianjianbao\dianjianbao-web\target\ROOT]
[INFO] Processing war project
[INFO] Copying webapp webResources [G:\dianjianbao\dianjianbao-web/src/main/webapp] to [G:\dianjianbao\dianjianbao-web\target\ROOT]
[INFO] Copying webapp resources [G:\dianjianbao\dianjianbao-web\src\main\webapp]
[INFO] Webapp assembled in [47027 msecs]
[INFO] Building war: G:\dianjianbao\dianjianbao-web\target\ROOT.war
[INFO]
[INFO] --- jcv-maven-plugin:0.0.3:process (process) @ dianjianbao-web ---
[INFO] ===================JCV==========================
[INFO]       _  _______      __
[INFO]      | |/ ____\ \    / /
[INFO]      | | |     \ \  / /
[INFO]  _   | | |      \ \/ /
[INFO] | |__| | |____   \  /
[INFO]  \____/ \_____|   \/
[INFO]
[INFO]
[INFO] find suffixs size:1
[INFO] build webRootName:ROOT
[INFO] build sourceEncoding:UTF-8
[INFO] web app Dir:G:\dianjianbao\dianjianbao-web\src\main\webapp
[INFO] out Dir:G:\dianjianbao\dianjianbao-web\target
[INFO] system is linux:false
[INFO] css method is :md5FileName
[INFO] js method is :md5FileName
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:35 min
[INFO] Finished at: 2017-03-10T10:57:44+08:00
[INFO] Final Memory: 10M/29M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:process (process) on project dianjianbao-web: Execution process of goal com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:pr
ocess failed: Illegal/unsupported escape sequence near index 35
[ERROR] G:\dianjianbao\dianjianbao-web\src\main\webapp\
[ERROR] ^
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:process (process) on project dianjianbao-web: Execution process of goal
com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:process failed: Illegal/unsupported escape sequence near index 35
G:\dianjianbao\dianjianbao-web\src\main\webapp\
                                   ^
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution process of goal com.iqarr.maven.plugin:jcv-maven-plugin:0.0.3:process failed: Illegal/unsupported escape sequence near index 3
5
G:\dianjianbao\dianjianbao-web\src\main\webapp\
                                   ^
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 35
G:\dianjianbao\dianjianbao-web\src\main\webapp\
                                   ^
        at java.util.regex.Pattern.error(Pattern.java:1924)
        at java.util.regex.Pattern.escape(Pattern.java:2416)
        at java.util.regex.Pattern.atom(Pattern.java:2164)
        at java.util.regex.Pattern.sequence(Pattern.java:2097)
        at java.util.regex.Pattern.expr(Pattern.java:1964)
        at java.util.regex.Pattern.compile(Pattern.java:1665)
        at java.util.regex.Pattern.<init>(Pattern.java:1337)
        at java.util.regex.Pattern.compile(Pattern.java:1022)
        at java.lang.String.replaceFirst(String.java:2167)
        at com.iqarr.maven.plugin.JCVMojo.getAllCssFile(JCVMojo.java:432)
        at com.iqarr.maven.plugin.JCVMojo.execute(JCVMojo.java:184)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
G:\dianjianbao\dianjianbao-web>`

**Comment by byzy** [comment]
感谢提供Bug,由于我是在linux 下开发，没有考虑到windows,等下就修复该bug.

**Comment by byzy** [comment]
bug 以修复，请使用<version>0.0.5</version>　，可以直接下载到本地安装，稍后将会同步到中央仓库. @Ltaimao
