### ISSUE TITLE
不配置baseJsDomin或者baseCssDomin会抛空指针

### ISSUE THREAD

**Issue by liukai237** [byzy/jcv-maven-plugin#4]
上述两个配置并没有说明是必须的。

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building fcsc.wechat 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jcv-maven-plugin:0.0.6:process (default-cli) @ fcsc.wx ---
[INFO] =================================JCV====================================
[INFO]       _  _______      __ 
[INFO]      | |/ ____\ \    / / 
[INFO]      | | |     \ \  / /  
[INFO]  _   | | |      \ \/ /   
[INFO] | |__| | |____   \  /    
[INFO]  \____/ \_____|   \/    
[INFO]                          
[INFO]                          
[INFO] find suffixs size:1
[INFO] build sourceEncoding:UTF-8
[INFO] out Dir:/Users/liukai/workspace/fcscplatform_bondtype/fcsc.wx/target/fcscwx
[INFO] system is linux:true
[INFO] css method is :MD5FileName_METHOD
[INFO] js method is :MD5FileName_METHOD
[INFO] build webRootName:fcscwx
[INFO] web app Dir:/Users/liukai/workspace/fcscplatform_bondtype/fcsc.wx/src/main/webapp
[ERROR]  the file process error :/Users/liukai/workspace/fcscplatform_bondtype/fcsc.wx/src/main/webapp/WEB-INF/jsp/error.jsp
java.lang.NullPointerException
	at com.iqarr.maven.plugin.support.DefaultProcessFactory.processlink(DefaultProcessFactory.java:502)
	at com.iqarr.maven.plugin.support.DefaultProcessFactory.processVersion(DefaultProcessFactory.java:461)
	at com.iqarr.maven.plugin.support.DefaultProcessFactory.processVersion(DefaultProcessFactory.java:463)
	at com.iqarr.maven.plugin.support.DefaultProcessFactory.processCSSVersion(DefaultProcessFactory.java:258)
	at com.iqarr.maven.plugin.support.AbstractProcessFactory.doProcessPageFile(AbstractProcessFactory.java:189)
	at com.iqarr.maven.plugin.JCVMojo.execute(JCVMojo.java:204)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
[INFO] --------------------------------- copy untreated file file size: 17
[INFO] --------------------------------- process success file size: 0
[INFO] ===============  Total time [68 millisecond]===========================
[INFO] ========================================================================
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.395s
[INFO] Finished at: Thu Apr 20 15:04:19 CST 2017
[INFO] Final Memory: 4M/123M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

**Comment by byzy** [comment]
感谢反馈，你现在随便配置一个,以解除这个错误，后面会进行修复
```xml
<baseJsDomin>
<param>http://script.iqarr.com</param>
 </baseJsDomin>```
@liukai237

**Comment by byzy** [comment]
插件以发布，中央仓库同步到其他仓库要3到4小时,之后在运行`mvn clean -U package`
@liukai237

**Comment by liukai237** [comment]
非常好的插件，已经用上了，配置稍显麻烦，文档有待完善。赞一个！
